travis:
  secure:
    BINSTAR_TOKEN: qXuPelvlnl8lVUH0ikhX5WyxC3AFnf9ww+M9kq2dW0L6gsn+4fDra6jTV1dpgjGlTwNpAt7IwT627nbFrLNjAM/bIGOjewH6zszZ6ouY0lk/4w+izA/Jeb8FjX74e8LI8FFmkgc6Z3YLtlA4I904Mf0VKj7/0RtySgNqaol8P5/fYT5+FJLxUKVlvIdn0/XVejzsHh1BOfQPeViO8KeIkKVbcnqLIfv/xV7Zuz4zAI2y4dEPkL4LJAwbzR/KciR6MAtiutnqAc7c0cbCt/QJFRXFk2WtNnzNWtrRljl7xD+e+1SIqxkYw4Zw8oXNfkaRk/QkfNXupQ+IB4Yrwr8nVztSOWC9hZrRQGICLuKstXiL1yOdR7XuUwZL51+IgcHXn0Li5OoTGU9F9o6X2LTDjMYktrJcNIxG7YQU3Vsau0fOsKLx287mmlzyDBRe0oHpFdjQFQijG/ATK/e5FwoQtOqgfAWK+C88IT5gB0CuSKVkEyB/r6tSQIquohb/17zTDr6WtEIoL8CPaTfg0jbUpLmUb2/niIipZeecd9Cw7swXZUPhS77QXuG/gKjWjFxDPuefwb/FcJqbwUGNA803GTk3krP6lD+raI81yn4G94CgdbEHle5kqFfF8j2NPpIKRGP9d958ycaznR3cFdli7nqsAQZIR/TBb4NyJeltyy4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
