travis:
  secure:
    BINSTAR_TOKEN: IVQ6YOFL51VswDUfbPIkLAo2J/vEryIlwIIcYk8ZrP4kT/Imr6f5SaK9+tX/rcBXIiTlVI9dRKLXRjZR+kXjelrSk8Dp6lEQk54qVzev3MxbD7sRkff38wbeY2sLtcQdU5Nj6PKujr0n1Ce2g7/KDQpNI4kH+HSOE0MSJZNodqjEn0jrWkaGvJvy9tXQeMqBflaF8G2DpRhLJW9XBP3LDY0cMQCN0EeQr3CRs5XpEw6UrqjCTchdOfox988tiN1xQhdLDD/Ik7cn0Cf58+h16wsU7NEZL/YQsBr222LRsjFweeGdMk8Z2El9AA7XBTThBmR4CgCNgkLcZey2YMQ40uzqvgWJpvERRqjoYn6VGWA6Tz4V6QM/Lr/3i3VhUW1kOBipaxq22aSWn8pBR8chqoMiIANWnvIaIh2VRBx0YMM7+oCLQsjLsLaWBs9gAWH/KISyNOE5h6oK7gP5J2Xinjv2ygTWuFyUEoyr01zK+L2AAlryUNgVfNeVgvdkbz5ci9usSBFnUL0SbR4PrhKVD75eNboy8JjHJWX6UwZDlEvX8ujQSaQ6SZYD4JAgvY8qPMS4EFDWdbJl7fGFqdk5bDJMDVZO2QyZZ6ZXUfjWcLa/QE3EVN85EWvbITQYf4aDrgYDu7osDKV5FdwvgGnBpgZAP5+cgRXDiAYr9L6bSqY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
